### ISSUE TITLE
Impossible to read config values for KDE themes (color schemes?)

### ISSUE THREAD

**Issue by ripefig** [daehruoydeef/Yin-Yang#30] opened 2019-09-05 17:54 UTC
Widget too small to display content:

![image](https://user-images.githubusercontent.com/45201036/64366564-2da71900-d01f-11e9-91ba-4228cc05dae1.png)

**Comment by l0drex** [comment] 2020-04-13 10:32
Duplicate of #23

**Closed** 2020-04-19 10:31 UTC
Labels: help wanted
